### ISSUE TITLE
Failed to share with FaceBook

### ISSUE THREAD

**Issue by hkurokawa** [konifar/material-cat#27]
## Description

When I tried to share the app with Facebook, a Facebook share dialog was shown for a few seconds and soon disappeared.  The log message indicates that your app setting is in Sandbox mode.  Could you check the setting?

I suspect your Facebook account is registered as developer so you might not see this behaviour on your device.  Please try to reproduce it with another Facebook account.
## Steps
1. Install Facebook app on your phone and log in with a Facebook account
2. Launch Material Cat
3. Tap the share button on the right bottom
4. Tap Facebook icon
## Result

After step 4, a share dialog is shown for a few seconds but soon disappeared.
## Expected Result

After step 4, a share dialog is shown and I can share Material Cat on Facebook.

**Comment by hkurokawa** [comment]
I changed your code a bit and logged callback message, which said:

```
08-09 08:52:44.804  17537-17537/com.konifar.materialcat E/MainActivity﹕ Failed to open share dialog: Failed to get app name.
    Failed to get app name.
            at com.facebook.internal.NativeProtocol.getExceptionFromErrorData(NativeProtocol.java:695)
            at com.facebook.share.internal.ShareInternalUtility.handleActivityResult(ShareInternalUtility.java:184)
            at com.facebook.share.internal.ShareInternalUtility$3.onActivityResult(ShareInternalUtility.java:276)
            at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:82)
            at com.konifar.materialcat.MainActivity.onActivityResult(MainActivity.java:225)
            at android.app.Activity.dispatchActivityResult(Activity.java:6192)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
            at android.app.ActivityThread.access$1300(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

[A Stackoverflow](http://stackoverflow.com/questions/19943807/where-does-this-error-come-from-error-com-facebook-facebookexception-failed-t) indicates it is because your app setting is in sandbox mode.  Can you check it on Facebook Developer page?

Thank you for your support in advance.

**Comment by konifar** [comment]
@hkurokawa Thank you for detailed information! I'll check soon :+1:

**Comment by konifar** [comment]
@hkurokawa You are right. My facebook app is development mode now.

> A Stackoverflow indicates it is because your app setting is in sandbox mode. Can you check it on Facebook Developer page?

I'll submit for approval in developer page.

**Comment by konifar** [comment]
My facebook app is approved. And I checked sharing with facebook with test user.
Can you check?

**Comment by hkurokawa** [comment]
Hi,

Thank you for your prompt fix!  I have verified I could share the app with Facebook.  Closing the issue.
